### ISSUE TITLE
Ensemble method section seems out of place

### ISSUE THREAD

**Issue by allaway** [jaybee84/ml-in-rd#101]
As discussed on Aug 24 call, ensemble section might need to be moved.

My thought was that it go after we describe the independent methods or in the outlook section, and make it relatively more succinct than at present. 

Another suggestion in #98 from @jaybee84 was to move to the model-complexity section.

**Comment by jaybee84** [comment]
adding this to my plate for now... will move around this section and see what makes for a better flow.
