### ISSUE TITLE
Rewrite: regularization in the context of making simpler models

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#112]

**Comment by jaybee84** [comment]
Adding other regularization methods as mentioned in  https://github.com/jaybee84/ml-in-rd/pull/109/files#r482443696

**Comment by jaclyn-taroni** [comment]
In #114, I proposed to include text around feature selection & feature learning in the first section (formerly `heterogeneity`). This addition would provide helpful context for the model complexity section.  The scope of this change would basically be the introduction to the first section. For reference, the text of the TODOs from [that section](https://github.com/jaybee84/ml-in-rd/pull/114/files#diff-8a83757df2dec087a0b8328c92a09884R5-R6) is:

```
<!-- TODO: Talk about curse of dimensionality, etc. or even how interpreting many features for biological discovery can be somewhat challenging. -->
<!-- TODO: If we talk about *feature selection* in addition to feature/representation learning, that might set up model complexity nicely! --> 
```
