### ISSUE TITLE
rewrite: improve heterogeneity anecdote 

### ISSUE THREAD

**Issue by allaway** [jaybee84/ml-in-rd#113]
to address comments in #109

**Comment by jaclyn-taroni** [comment]
Now that the heterogeneity section is being restructured to be more general (#114), there are additional changes we need to make to the original heterogeneity section. Specifically, we expect that the text originally about dimensionality reduction will be broken out and expanded upon as it's own section and we'll reframe discovering/visualizing heterogeneity as a use case or motivation for dimensionality reduction. Here are comments in [that section](https://github.com/jaybee84/ml-in-rd/pull/114/files#diff-8a83757df2dec087a0b8328c92a09884R34) from #114 for reference:

```
#### Visualization and correction of technical effects

<!-- TODO: Use the section above to introduce this (assessment of batch effects, etc.) as a specific use case/motivation for the methods introduced above that is perhaps exacerbated in rare diseases. -->

<!-- There can be structure in our data that is not related to what we want to study... -->
```
