### ISSUE TITLE
Add your thoughts from reviewing the latest version of the article on google doc

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#125]
The article is going through some iterations on google doc. The current version is here: https://docs.google.com/document/d/1ZIjUnRRj5SIbBW8aqTiRAQIg4aSY8nnQ/edit?ts=5fc83ef2#

Our goal is to pause editing on the google doc and port it back here. So please note your thoughts about the current version of the article here in this issue.

**Comment by jaclyn-taroni** [comment]
I took a bunch of handwritten notes on a PDF version where I accepted all the changes (yes, on my iPad 🤩 😂 ). The notes I took are mostly related to wordsmithing, where I think having me file a PR would probably be more efficient than noting it here. I'm going to propose that we port it back over to Google Docs before I take a pass over all sections but the last one. @jaybee84 I think you should port your comment about making the "Using composite approaches can be a powerful strategy" section into a challenge-solution format into a GitHub issue!

**Comment by jaybee84** [comment]
@jaclyn-taroni Done!
