### ISSUE TITLE
Consider Challenge-Solution format for "Using composite approaches" section 

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#128]
In the examples, the aggregation of the different approaches (i.e. regularization, representation, prior data) is present but not highlighted. The rare disease aspect of the implementation also needs to be highlighted a bit more

Is it possible to use a challenge-solution format to describe these two examples, i.e. in example 1, challenge 1=small dataset, solution =representation learned from large dataset, challenge 2 = multiple studies, solution = ...

**Comment by jaybee84** [comment]
Linking the one unresolved comment from #120 here: https://github.com/jaybee84/ml-in-rd/pull/120#discussion_r516103061

**Comment by jaclyn-taroni** [comment]
Closed via #139
