### ISSUE TITLE
protect master?

### ISSUE THREAD

**Issue by allaway** [jaybee84/ml-in-rd#14]
Feel free to close if this doesn't make sense with manubot, but I would have assumed master should be protected, i.e. require a reviewed PR. This doesn't appear to be the case as I just inadvertently pushed to master :)

**Comment by jaybee84** [comment]
This definitely makes sense... I thought that was the case already, but maybe I missed something...

**Comment by jaybee84** [comment]
done... 

also set a draft-branch as default (analogous to "develop" branch in golem) :)
