### ISSUE TITLE
Round Robin Edits

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#146]
The manuscript is ready for another round of edits. All the figures are added in the article and have been cited in appropriate places.  I tried adding png/tiff versions of figures in addition to pdfs, but none of the versions rendered in the pdf/html version of the manuscript. Still trying to troubleshoot that, so please look at the `/content/images/figures/pdfs` directory to review the appropriate figure.

Lets do some aggressive pruning of text to tighten up the manuscript :)

Few issues to address as we are going through the edits:
#143 
Any remaining TODOs
Adding details to figure captions

Order of Round Robin: (Please tag the next person in line for review of your edits in the PR)
@jaybee84 
@jaclyn-taroni 
@allaway 
@cgreene

**Comment by jaybee84** [comment]
My edits are in... tagged @jaclyn-taroni on #147 :)

**Comment by jaclyn-taroni** [comment]
TODOs from my most recent pass for your reference @allaway:

* Opening sentence of synopsis should be specific about what kind of technological advances we're talking about.
* We use the terms "label-noise" and "high label-uncertainty" somewhat interchangably, is there a way to stick to one of these terms/phrases? (Relevant to: `02.intro.md` and `04.model-complexity.md`)
* "Fully integrate" dimension reduction figure into text of `03.heterogeneity.md` -> flesh out figure legends (#150). 
* Citation for "Regular ensemble learning has shown limited success in rare disease datasets where the label-uncertainty can be high." in 04.model.complexity.md line 11

**Comment by allaway** [comment]
I just realized that I kind of missed the first half of this: 
>"Fully integrate" dimension reduction figure into text of 03.heterogeneity.md -> flesh out figure legends (#150).

I'll take a stab now and ask @jaybee84 to review before exporting to doc for Justin's review.
