### ISSUE TITLE
gh-pages not working 

### ISSUE THREAD

**Issue by allaway** [jaybee84/ml-in-rd#17]
Ci appears to be working but the html and pdf links are 404ed.

**Comment by cgreene** [comment]
Is this intended? If not intended, then we need to follow the additional steps listed in the github actions setup instructions.

**Comment by allaway** [comment]
Not intended, we just discovered it :) Thanks for pointing us in that direction!

**Comment by cgreene** [comment]
Ahh - I wasn't sure since the repo was private :)

**Comment by jaybee84** [comment]
For our purposes, it seems that the [GH Action artifacts](https://github.com/greenelab/covid19-review/blob/master/INSTRUCTIONS.md#how-can-i-see-my-change) may be sufficient 

[Also see here for more context](https://github.com/manubot/rootstock/issues/341)
