### ISSUE TITLE
Revisions: Introduction

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#173]
Please read this section from the point of view of an audience less familiar with ML. Jot down any questions that occur to you while reading this section.

**Comment by jaclyn-taroni** [comment]
Notes I had:

* In referencing the systematic review on application of ML in RD, remove the references to specific approaches (e.g., SVM) and just stick to the number of studies and diseases
* Define machine learning and move descriptions of unsupervised and supervised machine learning from the "definitions" section to the intro and integrate them in the following ways:
  * Use a specific example (or two) of supervised machine learning applications in this context. Tie this into gold and silver standard discussion. Can also use a specific example here that's about precision medicine in common diseases if we'd like.
  * Likewise, what's a specific example of how one would use unsupervised machine learning in this context? That should come right after the definition of unsupervised machine learning.
* When we talk about bad things ™️  that can happen like unstable performance - what would that look like in someone's hands (e.g., in practice)? Why is that bad?
