### ISSUE TITLE
Revisions: manage complex high dimensional rare disease data

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#174]
Please read this section from the point of view of an audience less familiar with ML. Jot down any questions that occur to you while reading this section.

**Comment by jaclyn-taroni** [comment]
* Expand and/or simplify to more "plain language" the sentence about increased sparsity, etc. 
* Walk through PCA briefly – I'd say talking about it in the context of feature construction is probably the most relevant here? And maybe a sentence or two about the conceptual differences in t-SNE and UMAP (and/or what are they thought to be better at) 
* I think we do want to retain the discussion of technical variables, but the sentence about "Other approaches like reprocessing the data..." seems somewhat out of place to me in the current version of this section. Would it be useful to talk about that in the intro somehow as part of a specific example or "table setting" for challenges?

**Comment by dvenprasad** [comment]
Just jotting down questions that popped into my head as I read through. 

- What are hyperparameters?

- `Dimensionality reduction, or more fundamentally, representation learning` is this implying that both dimensionality reduction and representation learning are the same?

**Comment by jaybee84** [comment]
Adding the following just to revisit what we had mentioned to do:

- `We will revise the sections to include a synthesis of the machine learning concepts before transitioning to a few examples of application of these concepts in rare disease for the benefit of the readers.`
- `We will also refine the headers to provide more clarity to the readers.`
