### ISSUE TITLE
Revisions: Build upon prior knowledge and indirectly related data

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#176]
Please read this section from the point of view of an audience less familiar with ML. Jot down any questions that occur to you while reading this section.

**Comment by jaclyn-taroni** [comment]
* For the knowledge graph section, are there specific examples of knowledge graphs that are specific to a particular common disease context (e.g., BRCA) that we can use as contrast?

**Comment by dvenprasad** [comment]
- What kinds of data modality? 

- What does encoding method mean?

> While multitask learning classifiers use shared representations to learn multiple related but individual predictions (tasks) simultaneously [@https://www.doi.org/10.1023/a:1007379606734], few-shot learning generalizes a model trained on related tasks to a new task with limited labeled data (e.g., the detection of a patient with a rare disease from a low number of examples of that rare disease) 
- ^^^ Could we add an example for multitask learning, like there is for few shot learning? I know there's an example later on but I think it might help if people can compare as we introduce it. (snippet below)

**Comment by allaway** [comment]
>For the knowledge graph section, are there specific examples of knowledge graphs that are specific to a particular common disease context (e.g., BRCA) that we can use as contrast?
 
@jaclyn-taroni, Can you clarify this for me - specifically, what the contrast is that you are looking for? I think that KGs could be used for really any disease, regardless of rarity, so I'm not sure what the contrast should be highlighting.

**Comment by allaway** [comment]
@dvenprasad, 

> What kinds of data modality?

The data types are described a couple of sentences later. Do you think I should move them up to this sentence?

Thanks!

**Comment by jaclyn-taroni** [comment]
> Can you clarify this for me - specifically, what the contrast is that you are looking for? I think that KGs could be used for really any disease, regardless of rarity, so I'm not sure what the contrast should be highlighting.

Yes, KGs could be used for any disease.

If a disease is well-studied enough, one could presumably build a context-specific knowledge graph. If you can't do that, even more reason to "borrow" from more general KGs. Does that make sense?

**Comment by allaway** [comment]
Yes, that makes sense. Thanks!

**Comment by jaybee84** [comment]
@jaybee84 to split out the multitask learning part of this section out into a separate issue

**Comment by jaybee84** [comment]
Adding the following just to revisit what we had mentioned to do:

- `We will revise the sections to include a synthesis of the machine learning concepts before transitioning to a few examples of application of these concepts in rare disease for the benefit of the readers.`
- `We will also refine the headers to provide more clarity to the readers.`

**Comment by jaclyn-taroni** [comment]
I think this can be closed, so I'm going to close it. Please feel free to reopen if you disagree!
