### ISSUE TITLE
Revisions: Using composite approaches can be a powerful strategy

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#177]
Please read this section from the point of view of an audience less familiar with ML. Jot down any questions that occur to you while reading this section.

**Comment by jaclyn-taroni** [comment]
* Update the title of section to reflect powerful strategy for what per reviewer comment
* There was an earlier version of this section that I wrote when I thought we were writing for a biological audience, but I think that got edited in Google Docs? We should see if we can find it and "roll this back" as a starting point.

**Comment by jaclyn-taroni** [comment]
I spent some time with this yesterday and came to the conclusion that it might be better to wait until #174, #175, and #176 are addressed. If I recall correctly, this is the approach we used originally. It makes sense that the writing in this section would depend on exactly what we talk about before we get here & tie it together.

**Comment by jaybee84** [comment]
Adding the following just to revisit what we had mentioned to do:

- `We will revise the sections to include a synthesis of the machine learning concepts before transitioning to a few examples of application of these concepts in rare disease for the benefit of the readers.`
- `We will also refine the headers to provide more clarity to the readers.`
