### ISSUE TITLE
Revisions: Outlook

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#178]
Please read this section from the point of view of an audience less familiar with ML. Jot down any questions that occur to you while reading this section.

**Comment by jaclyn-taroni** [comment]
I thought this section read pretty well, even with our potential change in audience. However, I think that it might be the case (much like the intro!) that this changes as we edit the rest of the document. One thing I'll note is that a reviewer brought up expanding our comparisons to precision medicine and I think this section might be a natural place to do that.
