### ISSUE TITLE
Revisions: Figure 1 -- New Figure 2

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#179]
Please take a look at this figure from the point of view of an audience less familiar with ML. What are some of the points that are confusing ?

**Comment by dvenprasad** [comment]
Based on the review this is what I interpreted.
The way we represent the samples and datasets is not uniform. In this we have used shapes to represent datasets but everywhere else we have used the shaped to represent samples. So we need to reiterate and find a different way to represent datasets, i.e., not a shape.

**Comment by jaclyn-taroni** [comment]
Per @jaybee84 - turn this into a representation learning figure, which is covered in the first section on dimensionality reduction and in the section on multi-task learning, etc.

**Comment by jaclyn-taroni** [comment]
In terms of turning this into a representation learning figure - what if we started by getting rid of panels **a** and **d** and then simplifying / stripping away some of the text? I'd say in that context we can probably remove the shape as a dataset concept from this figure. I do think **b** and **c** are a good start wrt the points we're trying to make.

**Comment by jaclyn-taroni** [comment]
Additional thoughts I had today:

- Add a panel between the current b and c that takes two original features that do not show an obvious pattern in the heatmap and make a scatter plot (that also doesn't have an obvious pattern)
- Then between new scatter plot ☝🏻 and the current scatter plot we could have arrows with graphics that represent different approaches (e.g., matrix factorization, neural network, etc.)

**Comment by dvenprasad** [comment]
Adding current figure for reference
![Screen Shot 2021-08-13 at 3 42 29 PM](https://user-images.githubusercontent.com/15315514/129410670-26e4f7d0-d1a9-46f5-859e-4d11bcf69cc4.png)

**Comment by dvenprasad** [comment]
Updated figure based on feedback:

![figure-1](https://user-images.githubusercontent.com/15315514/130264321-b866b8ae-fc86-44a1-b902-d8743cfa292c.png)

**Comment by dvenprasad** [comment]
New figure:
![figure-1](https://user-images.githubusercontent.com/15315514/132060120-a3e0b405-bf39-45cf-8744-efe3b9822e55.png)

**Comment by jaybee84** [comment]
@dvenprasad can you please add in the updated figure [here](https://github.com/jaybee84/ml-in-rd/tree/draft-branch/content/images/figures/pdfs)?

**Comment by dvenprasad** [comment]
![figure2-representation-learning](https://user-images.githubusercontent.com/15315514/151245569-96f09835-64d5-4aab-92db-f3b5a2d84711.png)
