### ISSUE TITLE
Revisit KG concepts in green and purple

### ISSUE THREAD

**Issue by allaway** [jaybee84/ml-in-rd#197]
See here: https://projects.invisionapp.com/freehand/document/I6gyvMiJB

**Comment by dvenprasad** [comment]
<img width="533" alt="Screen Shot 2021-12-01 at 5 03 20 PM" src="https://user-images.githubusercontent.com/15315514/144321491-5c36dc85-4f43-4e72-bb9a-fb3f513c3698.png">

**Comment by allaway** [comment]
I think it might be good to summarize the data types like so: 

genetic (e.g. sequencing data)
functional (e.g. curated pathways)
clinical (e.g. rare disease EHR data)
chemical (e.g. drug targets)
ontological data (e.g. clinical ontologies, phenotype ontologies)

**Comment by allaway** [comment]
For the purple to green text section I might add: 

calculate node embeddings (purple) -> identify possible drug-disease relationships  (green)
term mapping to knowledge graphs (purple) -> generate enriched datasets with expanded terminology, links between concepts

**Comment by allaway** [comment]
I think this can probably be closed, but reassigned to @dvenprasad in case there's anything else that needs to happen?
