### ISSUE TITLE
Round Robin 2022

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#205]
The manuscript is ready for another round of edits. Note: Figure 3 and Fig 5 are still WIP and the old version is still present in the text.

Order of Round Robin: (Please tag the next person in line for review of your edits in the PR)
@allaway
@jaclyn-taroni
@jaybee84

**Comment by jaybee84** [comment]
just keeping with the review flow :)

**Comment by allaway** [comment]
I think after my PR is merged, @cgreene is up? :)

**Comment by jaybee84** [comment]
Hi @cgreene, 

We have finished revising the manuscript according to the reviewer feedback from the last submission and are waiting for your review. Specifically the revisions aim to:
1. reach our target audience who are researchers in the rare disease domain who intend to develop solutions to meet the next generation of challenges in this space.
2. revise the introduction to expand upon the need for machine learning in rare disease.
3. frame the sections in a way that they are concept-first instead of method-first, and include a synthesis of the machine learning concepts before transitioning to a few examples of application of these concepts in rare disease for the benefit of the readers.
4. reduce jargon as much as possible.

Would you be able to add edits/feedback by **Jul 15, 2022**?

For easy viewability of the figures along with text I have generated a [google doc version](https://docs.google.com/document/d/1Jz8ZYjqfycslfJ7-ydfFlkLV67WQkFTMbylmdWDf0Qk/edit#) too in case that is more convenient to review.
