### ISSUE TITLE
Figures too large for text

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#218]
Hi @dvenprasad, can you please add resized figures so that they render better [alongside the text](https://jaybee84.github.io/ml-in-rd/)?

**Comment by dvenprasad** [comment]
Okay will resize.

Note for me:
>Image files should be just large enough to view when the screen resolution is set to 640 x 480 pixels.

**Comment by dvenprasad** [comment]
Figures 1 and 2 aren't rendered on the link. Is that expected?
