### ISSUE TITLE
Challenges in data generation and harmonization

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#4]
1. add seminal work references
2. add description

**Comment by allaway** [comment]
>Techniques to manage disparities in data generation are required to power robust analyses in rare diseases: Rarity of patients leads to heterogeneity in sample collection, causing disparities in the data. We will discuss how rigorous normalization and methodologies capturing sample-wise gene-set level information can help appropriate integration of disparate data points to power machine learning approaches11–13.

**Comment by allaway** [comment]
There's a lot to possibly talk about here, so let's break this down by data type: 

#####Gene expression: assessing heterogeneity
*MDS
*PCA
*tSNE
*UMAP

#####Gene expression: correcting heterogeneity
*batch effect correction methods (regression-based modeling of batch effects - [ComBat](https://doi.org/10.1093/biostatistics/kxj037), [limma](https://doi.org/10.1093/nar/gkv007))
*gene expression heterogeneity analysis methods ([sva](https://doi.org/10.1093/bioinformatics/bts034)) 
*among many others

#####Variant data: assessing heterogeneity 
*dimensionality reduction methods on binarized variant data

#####Variant data: correcting heterogeneity
*Filtering to enrich for computationally predicted high-impact mutations (SIFT, Polyphen, etc)
*Filtering out common variants in the population (ExAC, dbSNP VAF < 0.01) 
*Reprocessing raw data with a common pipeline
*Comparing to targeted sequencing panels that generally have a better detection rate
*Ensembling multiple variant calling tools. Anecdotally, we observed that a tumor variant detected on a targeted sequencing panel was only detectable in the whole exome sequencing data from the same [sample using DeepVariant](https://doi.org/10.1101/2019.12.19.871897)- this manuscript is accepted at Sci Data so need to revise the doi before submitting
*Methods like [SHEAR](https://doi.org/10.1186/1471-2164-15-84) for structural variant detection

**Comment by jaybee84** [comment]
adding this [paper](https://www.pnas.org/content/116/24/11878) for consideration in the high-impact mutation prediction point (along with SIFT and Polyphen) ... seems like a good resource for diseases with multigenic possibilities!  

(conflict of interest disclaimer: I may have a soft spot for ensemble RFs :P )

**Comment by allaway** [comment]
An important thing to acknowledge: batches/processing cores/institutions are often confounded by the biological variables, like tumor type, disease state, etc.
