### ISSUE TITLE
AI and Multi-Omics for Rare Diseases: Challenges, Advances and Perspectives

### ISSUE THREAD

**Issue by allaway** [jaybee84/ml-in-rd#40]
@jguinney pointed me towards this review. Definitely worth reading, and considering what our perspective paper will add to the literature vs this!

**Comment by jaybee84** [comment]
Is this what you were referring to: https://www.frontiersin.org/research-topics/13783/ai-and-multi-omics-for-rare-diseases-challenges-advances-and-perspectives#overview? 

The review google is pointing me to is this: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6947640/  (the one that you mentioned in another issue)

**Comment by allaway** [comment]
Oops haha. Yes, that is the link!

**Comment by jaybee84** [comment]
Ah ok! ... That seems to be a new research topic that is inviting submissions for perspectives! so I got confused :)

**Comment by allaway** [comment]
Yeah, sorry, I wasn't very clear. 

I guess my thought is that this is perhaps a more crowded topic than I initially realized, so we'll need to consider the questions they raise when we write our perspective, and think about how these questions overlap with what we are addressing!

**Comment by jaybee84** [comment]
That's a good point!
I am copying some of their points here just to serve as a quick reminder for us and maybe we can try to address some of these contexts as we are discussing our respective sections (as applicable).

- The application of AI in RD: how AI can solve/help RD diagnostic?
- AI approaches to solve RDs challenges such as low diagnostic rates, reduced number of patients, geographical dispersion, limited annotated data.
- Limitations of current AI approaches and how can we improve it
- Development or application of multi-omics methods for RD diagnosis
- Novel statistical methods for multi-omics data integration in RD

**Comment by allaway** [comment]
Closing this - no clear action item and trying to improve my issue sanitization/cleanup :)
