### ISSUE TITLE
NOMINATOR Rare tumor therapy matching trial

### ISSUE THREAD

**Issue by allaway** [jaybee84/ml-in-rd#41]
Saw this good thread describing this trial presented at ASCO today: 
https://twitter.com/jamienholloway/status/1266822612149309441/photo/1

Essentially, it's a trial where they run a sequencing panel on rare tumors, find possible actionable mutations, and match them to a drug if there's an actionable variant. Only half of the tumors have a (possibly) actionable variant, so this approach alone won't be sufficient.

This is not ML-specific, but if we can find the abstract, it might be a good reference to contextualize the "where we're currently at in using genomics to understand and treat rare disease" vs the vision of where we could go.

**Comment by jaybee84** [comment]
Seems like this is an Australian clinical trial!
found the following related links: 
https://www.wehi.edu.au/news/genomic-sequencing-offers-new-hope-rare-cancers
https://www.anzctr.org.au/Trial/Registration/TrialReview.aspx?id=371145
https://www.cart-wheel.org/page/93/nominator-for-rare-cancers

**Comment by allaway** [comment]
Closing becasue this is too clinical for this perspective
