### ISSUE TITLE
Representation Learning write up

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#5]
1. add seminal work references
2. add description

**Comment by jaybee84** [comment]
added @jaclyn-taroni since a lot of this will be included in transfer learning :)

**Comment by jaybee84** [comment]
Adding a couple of papers here as a note to explore if we decide to add causal inference :
1. https://papers.nips.cc/paper/7223-causal-effect-inference-with-deep-latent-variable-models.pdf
2. https://arxiv.org/pdf/1802.06310.pdf

**Comment by jaclyn-taroni** [comment]
Upon further consideration, I think a description of representation learning needs to come before what's getting added in #63. This section would cover DeepProfile ([Dincer et al. _bioRxiv._ 2018.](https://doi.org/10.1101/278739)) as one example of feature learning in rare diseases (using a VAE in AML, to be specific).

**Comment by jaybee84** [comment]
We discussed this in the meeting today, just adding it here so we can refer back to it. The section will add DeepProfile and also Biobombe to our perspective as an example of representation learning in the context of transfer learning. :)
