### ISSUE TITLE
A running list of definitions

### ISSUE THREAD

**Issue by jaclyn-taroni** [jaybee84/ml-in-rd#50]
As we add terms and concepts through pull requests (that are not in scope of #24), we'll use this issue as a running list.

**Comment by jaybee84** [comment]
dummy variable
bias
variance

**Comment by jaybee84** [comment]
bagging
boosting

**Comment by jaclyn-taroni** [comment]
* Supervised learning vs. unsupervised learning
* Feature and feature learning
* Transfer learning
* Multitask learning
* Few-shot learning

**Comment by allaway** [comment]
overfitting
generalizable

the second is maybe not necessary, but putting it here in case since the use is somewhat specific (haha) in this context.
