### ISSUE TITLE
Outlook section content

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#68]
Drop thoughts here for anything that can be included in the outlook section

**Comment by jaybee84** [comment]
Trust in machine learning: https://www.aclweb.org/anthology/N16-3020.pdf

**Comment by allaway** [comment]
We could highlight this area as a yet-untapped opportunity for data generation in tandem with methods development events like DREAM Challenges or hackathon-style events.

**Comment by jaybee84** [comment]
Jotting down some thoughts from our last meeting:

This section will focus on the following two areas:
1. Key pitfalls that the new practitioners should keep in mind/beware of while applying ML methods in rare diseases
2. How the major pitfalls in applying ML in rare diseases can be great opportunities for method development/data generation in moving the field forward

**Comment by jaybee84** [comment]
Adding @allaway's suggestions from today's meeting: highlight the two camps of ml-in-rd: methods used successfully for classification of disease landscape (and identification of rare disease in general, not a particular one) and methods used for mechanistic interrogation for a particular rare disease. While both have few examples, the emphasis so far have been on the former, while there is a great opportunity of developing new methods to tackle the latter harder problem.

**Comment by allaway** [comment]
Mention how data could be improved (besides just "moar n") to enable the application of certain methods. example here https://github.com/jaybee84/ml-in-rd/pull/63#discussion_r468084020

**Comment by jaclyn-taroni** [comment]
Discussed in today's meeting - we will have folks take notes on how they think this section should shape up during their round robin passes (#88).

**Comment by jaybee84** [comment]
discussed in today's meeting: Quantitative (AUROC, precision-recall) vs qualitative (logical progression of ensembling different algorithms i.e. integrative analysis, biomedical evaluation using prior evidence) evaluation of model performance

**Comment by jaybee84** [comment]
https://www.nature.com/articles/s41576-020-0257-5
