### ISSUE TITLE
Knowledge graph creation

### ISSUE THREAD

**Issue by jaybee84** [jaybee84/ml-in-rd#8]
1. add seminal work references
2. add description

**Comment by jaybee84** [comment]
https://github.com/callahantiff/PheKnowLator
https://het.io/repurpose/

**Comment by allaway** [comment]
https://www.biorxiv.org/content/10.1101/2020.04.30.071407v1.full.pdf

**Comment by allaway** [comment]
https://monarchinitiative.org/

**Comment by allaway** [comment]
https://elifesciences.org/articles/26726

**Comment by allaway** [comment]
Closed by 71
