### ISSUE TITLE
Section highlighting that successful approaches include multiple strategies

### ISSUE THREAD

**Issue by jaclyn-taroni** [jaybee84/ml-in-rd#82]
**Context:** I am working on #63. Breaking out stub that is currently the url last section about combining multiple strategies in a single approach/application into it's own issue. Here's the current stub:

> To be successful, machine learning approaches in rare diseases likely require the inclusion _multiple strategies_ discussed throughout.
> 
> PLIER and MultiPLIER studies as examples 
> * Representation learning from an arbitrary, large set of gene expression data
> * Prior knowledge
> * Regularization

**Comment by jaybee84** [comment]
The sparse-group LASSO approach incorporates prior knowledge into the regularization [@doi:10.1080/10618600.2012.681250].

**Comment by jaybee84** [comment]
#7 seems to be similar to this

**Comment by jaclyn-taroni** [comment]
This is probably a good fit for the outlook section (#68)
