### ISSUE TITLE
EDITING: Round robin

### ISSUE THREAD

**Issue by jaclyn-taroni** [jaybee84/ml-in-rd#88]
After #87 is completed, each contributor will go through the entire manuscript and (probably) cut 10-20% of other people's sections.

**Comment by allaway** [comment]
@allaway to go first
@jaybee84  to go second 
@cgreene to go third
@jaclyn-taroni to go fourth

**Comment by allaway** [comment]
Will reassign when done!

**Comment by jaclyn-taroni** [comment]
I'm going to unassign @allaway and instead assign myself per our discussion last week. As part of my edits, I am planning to follow up on #109 and address #110 and #111 (and the first sketch of #108).
