### ISSUE TITLE
What changes need to be made to the introduction?

### ISSUE THREAD

**Issue by jaclyn-taroni** [jaybee84/ml-in-rd#96]
As each person goes through their round robin pass (#88), it makes sense to take notes on what needs to goes into the introduction. @allaway has volunteered to take a look at this during his pass.

**Comment by jaybee84** [comment]
- experimental design
- gold-standard or silver standard dataset

**Comment by allaway** [comment]
I added definition for rare disease, and an abbreviation for machine learning (ML) that was used some places throughout but never defined. 

I think the intro could have some additional content to help the reader tie the major sections together , but i did not add this yet.

**Comment by allaway** [comment]
Closed - this was addressed.
